name: Place Tux CI
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10" # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: "x64" # optional x64 or x86. Defaults to x64 if not specified
          cache: "pip"

      - name: Install requirements for everything
        run: |
          pip install -r overlay/requirements.txt
          pip install -r artwork_builder/requirements.txt
          pip install -r coord_gen/requirements.txt
          pip install -r wallpaper_builder/requirements.txt

      - name: Copy raw files
        run: |
          mkdir .build
          cp ./artwork/tux/tux.png ./.build/tux_raw.png


      - name: Copy all images
        run: |
          cp -R ./artwork/ ./.build/artwork/

      - name: Set priority
        run: |
          cp ./priority.txt ./.build/priority

      - name: Build tux_coords.png
        run: |
          python coord_gen/coords.py --input ./artwork/tux/tux.png --output ./.build/tux_coords.png -x1 20 -x2 72 -y1 679 -y2 766

      - name: Build tux_combined_tux, tux_combined_allies & tux_combined_all.png
        run: |
          cd artwork_builder
          python gen_overlay_from_sources.py build_all.json
          python gen_overlay_from_sources.py build_allies.json
          python gen_overlay_from_sources.py build_tux_only.json
          cd ..

      - name: Build tux_overlay.png
        run: |
          cd overlay
          cp ../.build/tux_combined_all.png ./overlay_raw.png
          python explode_overlay.py
          cp ./out/overlay.png ../.build/tux_overlay.png
          cd ..

      - name: Build tux_overlay_mask
        run: |
          cd overlay
          python create_mask.py ../.build/tux_combined_all.png ../.build/tux_combined_all_mask.png
          cd ..

      - name: Update hash
        run: echo $(git rev-parse "$GITHUB_SHA") > ./.build/bot_hash

      - name: Update userscript
        run: |
          cp ./overlay/userscript.user.js ./.build/userscript.user.js
          cp ./overlay/userscript-blurfix.user.js ./.build/userscript-blurfix.user.js

      - name: Generate wallpaper
        run: |
          cd wallpaper_builder
          python gen_wallpaper.py ../artwork/tux/tux.png ../.build/tux_wallpaper.png 

      - uses: EndBug/add-and-commit@v9
        with:
          add: "./.build"
          committer_name: GitHub Actions
          committer_email: actions@github.com

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.build/
          keep_files: true
          full_commit_message: deploy image
